deploy: 218b55dc7d818e0a7204febd0a0dc1f9780c9e17

diff --git a/target/docker/task/process_dataset/convert_kaggle_h5ad_to_parquet/convert_kaggle_h5ad_to_parquet b/target/docker/task/process_dataset/convert_kaggle_h5ad_to_parquet/convert_kaggle_h5ad_to_parquet
--- a/target/docker/task/process_dataset/convert_kaggle_h5ad_to_parquet/convert_kaggle_h5ad_to_parquet
+++ b/target/docker/task/process_dataset/convert_kaggle_h5ad_to_parquet/convert_kaggle_h5ad_to_parquet
@@ -185,9 +185,17 @@ function ViashHelp {
   echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources/neurips-2023-kaggle/de_train.parquet"
   echo ""
+  echo "    --output_train_h5ad"
+  echo "        type: file, required parameter, output, file must exist"
+  echo "        example: resources/neurips-2023-kaggle/de_train.h5ad"
+  echo ""
   echo "    --output_test"
   echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources/neurips-2023-kaggle/de_test.parquet"
+  echo ""
+  echo "    --output_test_h5ad"
+  echo "        type: file, required parameter, output, file must exist"
+  echo "        example: resources/neurips-2023-kaggle/de_test.h5ad"
   echo ""
   echo "    --output_id_map"
   echo "        type: file, required parameter, output, file must exist"
@@ -418,9 +426,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "fastparquet" "anndata" "pandas"
 
 LABEL org.opencontainers.image.description="Companion container for running component task/process_dataset convert_kaggle_h5ad_to_parquet"
-LABEL org.opencontainers.image.created="2024-05-11T07:24:11Z"
+LABEL org.opencontainers.image.created="2024-05-13T14:54:22Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task-dge-perturbation-prediction"
-LABEL org.opencontainers.image.revision="10f8469a1950c9560eda197763dc30723f9dc3a7"
+LABEL org.opencontainers.image.revision="218b55dc7d818e0a7204febd0a0dc1f9780c9e17"
 LABEL org.opencontainers.image.version="main_build"
 
 VIASHDOCKER
@@ -608,6 +616,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_OUTPUT_TRAIN=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --output_train_h5ad)
+            [ -n "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ] && ViashError Bad arguments for option \'--output_train_h5ad\': \'$VIASH_PAR_OUTPUT_TRAIN_H5AD\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_TRAIN_H5AD="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_train_h5ad. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_train_h5ad=*)
+            [ -n "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ] && ViashError Bad arguments for option \'--output_train_h5ad=*\': \'$VIASH_PAR_OUTPUT_TRAIN_H5AD\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_TRAIN_H5AD=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --output_test)
             [ -n "$VIASH_PAR_OUTPUT_TEST" ] && ViashError Bad arguments for option \'--output_test\': \'$VIASH_PAR_OUTPUT_TEST\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_OUTPUT_TEST="$2"
@@ -617,6 +636,17 @@ while [[ $# -gt 0 ]]; do
         --output_test=*)
             [ -n "$VIASH_PAR_OUTPUT_TEST" ] && ViashError Bad arguments for option \'--output_test=*\': \'$VIASH_PAR_OUTPUT_TEST\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_OUTPUT_TEST=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_test_h5ad)
+            [ -n "$VIASH_PAR_OUTPUT_TEST_H5AD" ] && ViashError Bad arguments for option \'--output_test_h5ad\': \'$VIASH_PAR_OUTPUT_TEST_H5AD\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_TEST_H5AD="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_test_h5ad. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_test_h5ad=*)
+            [ -n "$VIASH_PAR_OUTPUT_TEST_H5AD" ] && ViashError Bad arguments for option \'--output_test_h5ad=*\': \'$VIASH_PAR_OUTPUT_TEST_H5AD\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_TEST_H5AD=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --output_id_map)
@@ -760,8 +790,16 @@ if [ -z ${VIASH_PAR_OUTPUT_TRAIN+x} ]; then
   ViashError '--output_train' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_OUTPUT_TRAIN_H5AD+x} ]; then
+  ViashError '--output_train_h5ad' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_OUTPUT_TEST+x} ]; then
   ViashError '--output_test' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT_TEST_H5AD+x} ]; then
+  ViashError '--output_test_h5ad' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_PAR_OUTPUT_ID_MAP+x} ]; then
@@ -847,8 +885,14 @@ fi
 if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN" ] && [ ! -d "$(dirname "$VIASH_PAR_OUTPUT_TRAIN")" ]; then
   mkdir -p "$(dirname "$VIASH_PAR_OUTPUT_TRAIN")"
 fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ] && [ ! -d "$(dirname "$VIASH_PAR_OUTPUT_TRAIN_H5AD")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_OUTPUT_TRAIN_H5AD")"
+fi
 if [ ! -z "$VIASH_PAR_OUTPUT_TEST" ] && [ ! -d "$(dirname "$VIASH_PAR_OUTPUT_TEST")" ]; then
   mkdir -p "$(dirname "$VIASH_PAR_OUTPUT_TEST")"
+fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TEST_H5AD" ] && [ ! -d "$(dirname "$VIASH_PAR_OUTPUT_TEST_H5AD")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_OUTPUT_TEST_H5AD")"
 fi
 if [ ! -z "$VIASH_PAR_OUTPUT_ID_MAP" ] && [ ! -d "$(dirname "$VIASH_PAR_OUTPUT_ID_MAP")" ]; then
   mkdir -p "$(dirname "$VIASH_PAR_OUTPUT_ID_MAP")"
@@ -869,10 +913,20 @@ if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN" ]; then
   VIASH_PAR_OUTPUT_TRAIN=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TRAIN")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_OUTPUT_TRAIN" )
 fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ]; then
+  VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TRAIN_H5AD")" )
+  VIASH_PAR_OUTPUT_TRAIN_H5AD=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TRAIN_H5AD")
+  VIASH_CHOWN_VARS+=( "$VIASH_PAR_OUTPUT_TRAIN_H5AD" )
+fi
 if [ ! -z "$VIASH_PAR_OUTPUT_TEST" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TEST")" )
   VIASH_PAR_OUTPUT_TEST=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TEST")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_OUTPUT_TEST" )
+fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TEST_H5AD" ]; then
+  VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TEST_H5AD")" )
+  VIASH_PAR_OUTPUT_TEST_H5AD=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TEST_H5AD")
+  VIASH_CHOWN_VARS+=( "$VIASH_PAR_OUTPUT_TEST_H5AD" )
 fi
 if [ ! -z "$VIASH_PAR_OUTPUT_ID_MAP" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_ID_MAP")" )
@@ -945,7 +999,9 @@ par = {
   'input_train': $( if [ ! -z ${VIASH_PAR_INPUT_TRAIN+x} ]; then echo "r'${VIASH_PAR_INPUT_TRAIN//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'input_test': $( if [ ! -z ${VIASH_PAR_INPUT_TEST+x} ]; then echo "r'${VIASH_PAR_INPUT_TEST//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'output_train': $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN+x} ]; then echo "r'${VIASH_PAR_OUTPUT_TRAIN//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_train_h5ad': $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN_H5AD+x} ]; then echo "r'${VIASH_PAR_OUTPUT_TRAIN_H5AD//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'output_test': $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST+x} ]; then echo "r'${VIASH_PAR_OUTPUT_TEST//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_test_h5ad': $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST_H5AD+x} ]; then echo "r'${VIASH_PAR_OUTPUT_TEST_H5AD//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'output_id_map': $( if [ ! -z ${VIASH_PAR_OUTPUT_ID_MAP+x} ]; then echo "r'${VIASH_PAR_OUTPUT_ID_MAP//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
 meta = {
@@ -969,12 +1025,15 @@ dep = {
 ## VIASH END
 
 
-def anndata_to_dataframe(adata):
-  adata.obs["control"] = adata.obs["split"] == "control"
-  metadata = adata.obs[['cell_type', 'sm_name', 'sm_lincs_id', 'SMILES', 'split', 'control']]
+def anndata_to_dataframe(adata, add_id=False):
+  obs_cols = ['cell_type', 'sm_name', 'sm_lincs_id', 'SMILES', 'split', 'control']
+  if add_id:
+    obs_cols = ["id"] + obs_cols
+
+  metadata = adata.obs[obs_cols]
 
   sign_logfc_pval = pd.DataFrame(
-    adata.X,
+    adata.layers["sign_log10_pval"],
     columns=adata.var_names,
     index=adata.obs.index
   )
@@ -985,18 +1044,30 @@ print(">> Load dataset", flush=True)
 input_train = ad.read_h5ad(par["input_train"])
 input_test = ad.read_h5ad(par["input_test"])
 
-print(">> Convert AnnData to DataFrame", flush=True)
-de_train = anndata_to_dataframe(input_train)
-de_test = anndata_to_dataframe(input_test)
+print(">> Add 'control' column", flush=True)
+input_train.obs["control"] = input_train.obs["split"] == "control"
+input_test.obs["control"] = input_test.obs["split"] == "control"
 
 print(">> Add 'id' to test", flush=True)
-de_test.reset_index(drop=True, inplace=True)
-de_test.reset_index(names="id", inplace=True)
+input_test.obs.reset_index(drop=True, inplace=True)
+input_test.obs.reset_index(names="id", inplace=True)
+
+print(">> Move X to layers", flush=True)
+input_train.layers["sign_log10_pval"] = input_train.X
+input_test.layers["sign_log10_pval"] = input_test.X
+del input_train.X
+del input_test.X
+
+print(">> Convert AnnData to DataFrame", flush=True)
+de_train = anndata_to_dataframe(input_train)
+de_test = anndata_to_dataframe(input_test, add_id=True)
 
 print(">> Create id_map data frame", flush=True)
 id_map = de_test[["id", "sm_name", "cell_type"]]
 
 print(">> Save data", flush=True)
+input_train.write(par["output_train_h5ad"], compression=9)
+input_test.write(par["output_test_h5ad"], compression=9)
 de_train.to_parquet(par["output_train"])
 de_test.to_parquet(par["output_test"])
 id_map.to_csv(par["output_id_map"], index=False)
@@ -1017,8 +1088,14 @@ fi
 if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN" ]; then
   VIASH_PAR_OUTPUT_TRAIN=$(ViashStripAutomount "$VIASH_PAR_OUTPUT_TRAIN")
 fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ]; then
+  VIASH_PAR_OUTPUT_TRAIN_H5AD=$(ViashStripAutomount "$VIASH_PAR_OUTPUT_TRAIN_H5AD")
+fi
 if [ ! -z "$VIASH_PAR_OUTPUT_TEST" ]; then
   VIASH_PAR_OUTPUT_TEST=$(ViashStripAutomount "$VIASH_PAR_OUTPUT_TEST")
+fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TEST_H5AD" ]; then
+  VIASH_PAR_OUTPUT_TEST_H5AD=$(ViashStripAutomount "$VIASH_PAR_OUTPUT_TEST_H5AD")
 fi
 if [ ! -z "$VIASH_PAR_OUTPUT_ID_MAP" ]; then
   VIASH_PAR_OUTPUT_ID_MAP=$(ViashStripAutomount "$VIASH_PAR_OUTPUT_ID_MAP")
@@ -1042,8 +1119,16 @@ if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN" ] && [ ! -e "$VIASH_PAR_OUTPUT_TRAIN" ]; the
   ViashError "Output file '$VIASH_PAR_OUTPUT_TRAIN' does not exist."
   exit 1
 fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ] && [ ! -e "$VIASH_PAR_OUTPUT_TRAIN_H5AD" ]; then
+  ViashError "Output file '$VIASH_PAR_OUTPUT_TRAIN_H5AD' does not exist."
+  exit 1
+fi
 if [ ! -z "$VIASH_PAR_OUTPUT_TEST" ] && [ ! -e "$VIASH_PAR_OUTPUT_TEST" ]; then
   ViashError "Output file '$VIASH_PAR_OUTPUT_TEST' does not exist."
+  exit 1
+fi
+if [ ! -z "$VIASH_PAR_OUTPUT_TEST_H5AD" ] && [ ! -e "$VIASH_PAR_OUTPUT_TEST_H5AD" ]; then
+  ViashError "Output file '$VIASH_PAR_OUTPUT_TEST_H5AD' does not exist."
   exit 1
 fi
 if [ ! -z "$VIASH_PAR_OUTPUT_ID_MAP" ] && [ ! -e "$VIASH_PAR_OUTPUT_ID_MAP" ]; then
